version: 1
formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(message)s"

handlers:
  file_size_handler:
    class: logging.FileHandler
    formatter: simple
    filename: logs/my_logfile.log

loggers:
  file_size_logger:
    level: DEBUG
    handlers: [file_size_handler]

# root:
#   level: DEBUG
#   handlers: [file_handler]