version: 1
formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(message)s"

handlers:
  rotating_file_handler:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: logs/my_logfile.log
    maxBytes: 10240
    backupCount: 3

loggers:
  file_size_logger:
    level: DEBUG
    handlers: [rotating_file_handler]

# root:
#   level: DEBUG
#   handlers: [file_handler]
